sonar.projectKey=psp-detector
sonar.projectName=PSP Detector
sonar.sources=src
sonar.tests=tests,src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.exclusions=dist/**,node_modules/**,build/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.json
