name: Create Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0, v1.1, etc.

  workflow_dispatch:  # Allow the workflow to be manually triggered

permissions:
  contents: write  # Allow write access to repository contents (required for creating releases)

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Get version from tag
      id: extract_version
      if: github.event_name == 'push'
      run: |
        TAG_NAME=${GITHUB_REF##*/}
        VERSION=${TAG_NAME#v}
        echo "::set-output name=version::$VERSION"

    - name: Zip app directory
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          VERSION="manual"
        else
          VERSION=${{ steps.extract_version.outputs.version }}
        fi
        zip -r "psp-detector-${VERSION}.zip" app/

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use the PAT instead of GITHUB_TOKEN
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.extract_version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: psp-detector-${{ steps.extract_version.outputs.version }}.zip
        asset_name: psp-detector-${{ steps.extract_version.outputs.version }}.zip
        asset_content_type: application/zip
