name: PR Validate

on:
  pull_request:
    paths:
      - 'src/**'
      - 'public/**'
      - 'assets/**'
      - 'tests/**'
      - 'package.json'
      - 'package-lock.json'
      - 'build.js'
      - 'playwright.config.ts'
      - 'tsconfig.json'
      - 'tsconfig.test.json'
      - 'eslint.config.mjs'
      - '.github/workflows/**'

jobs:
  pr-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Validate project (lint, typecheck, unit tests, build)
        run: npm run validate

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run integration tests (Playwright)
        run: npx playwright test tests/integration --project=chromium --reporter=line
