name: Build and Release Extension

on:
  push:
    branches:
      - main
    # Only run when relevant source/build/test files change (skip for docs-only edits)
    paths:
      - 'src/**'
      - 'public/**'
      - 'assets/**'
      - 'tests/**'
      - 'package.json'
      - 'package-lock.json'
      - 'build.js'
      - 'playwright.config.ts'
      - 'tsconfig.json'
      - 'tsconfig.test.json'
      - 'eslint.config.mjs'
      - '.github/workflows/**'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Validate project (lint, typecheck, unit tests, build)
        run: npm run validate

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run integration tests (Playwright)
        run: npx playwright test tests/integration --project=chromium --reporter=line

      - name: Get version from manifest
        id: manifest
        run: |
          VERSION=$(jq -r .version dist/manifest.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Archive dist folder
        run: zip -r psp-detector-${{ steps.manifest.outputs.version }}.zip dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.manifest.outputs.version }}
          name: psp-detector-${{ steps.manifest.outputs.version }}.zip
          body: "Automated build and release."
          files: psp-detector-${{ steps.manifest.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
